// Note: This file was generated by an LLM

use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;

const EPSILON: f32 = 1.0e-12;
const OCCUPIED_THRESHOLD_FACTOR: f32 = 1.0e-6;

macro_rules! log {
    ($($t:tt)*) => {
        web_sys::console::log_1(&format!($($t)*).into());
    };
}

// ============================================================================
// Geometry
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Point2D {
    pub x: f64, // longitude
    pub y: f64, // latitude
}

// ============================================================================
// Contours
// ============================================================================

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Contour {
    pub threshold: f32,
    pub rings: Vec<Vec<Point2D>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProbabilityContour {
    pub probability: f32,
    pub density_threshold: f32,
    pub rings: Vec<Vec<Point2D>>,
}

// ============================================================================
// Grid
// ============================================================================

pub struct EulerianGrid {
    lon_min: f64,
    lon_max: f64,
    lat_min: f64,
    lat_max: f64,
    cell_size: f64,
    nx: usize,
    ny: usize,

    // This stores either:
    // - concentration/weight for ordinary heatmaps; or
    // - probability mass for SAR mode.
    grid: Vec<f32>,

    smooth_kernel: [f32; 9],
}

impl EulerianGrid {
    pub fn new(
        lon_min: f64,
        lon_max: f64,
        lat_min: f64,
        lat_max: f64,
        cell_size: f64,
    ) -> Self {
        let valid_bounds =
            lon_min < lon_max &&
            lat_min < lat_max &&
            cell_size.is_finite() &&
            cell_size > 0.0;

        if !valid_bounds {
            return Self {
                lon_min: 0.0,
                lon_max: 1.0,
                lat_min: 0.0,
                lat_max: 1.0,
                cell_size: 1.0,
                nx: 1,
                ny: 1,
                grid: vec![0.0],
                smooth_kernel: Self::default_kernel(),
            };
        }

        let nx = (((lon_max - lon_min) / cell_size).ceil() as usize).max(2);
        let ny = (((lat_max - lat_min) / cell_size).ceil() as usize).max(2);

        Self {
            lon_min,
            lon_max,
            lat_min,
            lat_max,
            cell_size,
            nx,
            ny,
            grid: vec![0.0; nx * ny],
            smooth_kernel: Self::default_kernel(),
        }
    }

    fn default_kernel() -> [f32; 9] {
        [
            1.0 / 16.0,
            2.0 / 16.0,
            1.0 / 16.0,
            2.0 / 16.0,
            4.0 / 16.0,
            2.0 / 16.0,
            1.0 / 16.0,
            2.0 / 16.0,
            1.0 / 16.0,
        ]
    }

    pub fn clear(&mut self) {
        self.grid.fill(0.0);
    }

    #[inline]
    fn grid_index(&self, ix: usize, iy: usize) -> usize {
        iy * self.nx + ix
    }

    fn coordinate_to_cell(
        &self,
        lon: f64,
        lat: f64,
    ) -> Option<(usize, usize)> {
        if !lon.is_finite() || !lat.is_finite() {
            return None;
        }

        let fx = (lon - self.lon_min) / self.cell_size;
        let fy = (lat - self.lat_min) / self.cell_size;

        if fx < 0.0 || fy < 0.0 {
            return None;
        }

        let ix = fx.floor() as usize;
        let iy = fy.floor() as usize;

        if ix >= self.nx || iy >= self.ny {
            return None;
        }

        Some((ix, iy))
    }

    pub fn add_particle(
        &mut self,
        lon: f64,
        lat: f64,
        weight: f32,
    ) {
        if !weight.is_finite() || weight <= 0.0 {
            return;
        }

        let Some((ix, iy)) = self.coordinate_to_cell(lon, lat) else {
            return;
        };

        let index = self.grid_index(ix, iy);
        self.grid[index] += weight;
    }

    pub fn add_particles(
        &mut self,
        lons: &[f64],
        lats: &[f64],
        weights: Option<&[f32]>,
    ) {
        let n = lons.len().min(lats.len());

        for i in 0..n {
            let weight = match weights {
                Some(values) => values.get(i).copied().unwrap_or(0.0),
                None => 1.0,
            };

            self.add_particle(lons[i], lats[i], weight);
        }
    }

    // ========================================================================
    // Probability operations
    // ========================================================================

    pub fn total_mass(&self) -> f32 {
        self.grid
            .iter()
            .copied()
            .filter(|value| value.is_finite() && *value > 0.0)
            .sum()
    }

    pub fn normalize_probability(&mut self) {
        let total = self.total_mass();

        if total <= EPSILON || !total.is_finite() {
            return;
        }

        for value in &mut self.grid {
            if value.is_finite() && *value > 0.0 {
                *value /= total;
            } else {
                *value = 0.0;
            }
        }
    }

    // For equal-sized cells, probability mass and density have the same
    // ordering. This is appropriate for the current regular degree grid.
    pub fn hdr_density_threshold(
        &self,
        target_probability: f32,
    ) -> Option<f32> {
        let mut values: Vec<f32> = self
            .grid
            .iter()
            .copied()
            .filter(|value| value.is_finite() && *value > 0.0)
            .collect();

        if values.is_empty() {
            return None;
        }

        values.sort_by(|a, b| {
            b.partial_cmp(a)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        let total: f32 = values.iter().sum();

        if total <= EPSILON || !total.is_finite() {
            return None;
        }

        let target = target_probability.clamp(0.0, 1.0) * total;
        let mut cumulative = 0.0;

        for value in values.iter().copied() {
            cumulative += value;

            if cumulative + EPSILON >= target {
                return Some(value);
            }
        }

        values.last().copied()
    }

    pub fn occupied_threshold(&self) -> Option<f32> {
        let maximum = self
            .grid
            .iter()
            .copied()
            .filter(|value| value.is_finite() && *value > 0.0)
            .fold(0.0_f32, f32::max);

        if maximum <= EPSILON {
            None
        } else {
            Some(maximum * OCCUPIED_THRESHOLD_FACTOR)
        }
    }

    // ========================================================================
    // Smoothing
    // ========================================================================

    pub fn smooth(&mut self) {
        if self.grid.is_empty() || self.nx < 2 || self.ny < 2 {
            return;
        }

        let mut smoothed = vec![0.0; self.grid.len()];

        for iy in 0..self.ny {
            for ix in 0..self.nx {
                let mut sum = 0.0;

                for ky in -1..=1 {
                    for kx in -1..=1 {
                        let source_x = (ix as isize + kx)
                            .clamp(0, self.nx as isize - 1)
                            as usize;

                        let source_y = (iy as isize + ky)
                            .clamp(0, self.ny as isize - 1)
                            as usize;

                        let kernel_index =
                            ((ky + 1) * 3 + (kx + 1)) as usize;

                        let source_index =
                            self.grid_index(source_x, source_y);

                        sum += self.grid[source_index]
                            * self.smooth_kernel[kernel_index];
                    }
                }

                smoothed[self.grid_index(ix, iy)] = sum;
            }
        }

        self.grid = smoothed;
    }

    // ========================================================================
    // Ordinary concentration contours
    // ========================================================================

    pub fn generate_contours(
        &self,
        thresholds: &[f32],
    ) -> Vec<Contour> {
        thresholds
            .iter()
            .copied()
            .filter(|threshold| threshold.is_finite())
            .filter_map(|threshold| {
                let rings = self.marching_squares(threshold);

                if rings.is_empty() {
                    None
                } else {
                    Some(Contour { threshold, rings })
                }
            })
            .collect()
    }

    pub fn to_contour_geojson(
        &self,
        thresholds: &[f32],
    ) -> String {
        let contours = self.generate_contours(thresholds);
        let mut features = Vec::new();

        for contour in contours {
            for ring in contour.rings {
                if ring.len() < 3 {
                    continue;
                }

                let coordinates: Vec<Vec<f64>> = ring
                    .iter()
                    .map(|point| vec![point.x, point.y])
                    .collect();

                features.push(serde_json::json!({
                    "type": "Feature",
                    "geometry": {
                        "type": "Polygon",
                        "coordinates": [coordinates]
                    },
                    "properties": {
                        "concentration": contour.threshold
                    }
                }));
            }
        }

        serde_json::json!({
            "type": "FeatureCollection",
            "features": features
        })
        .to_string()
    }

    // ========================================================================
    // SAR probability contours
    // ========================================================================

    pub fn generate_probability_contours(
        &self,
        probabilities: &[f32],
    ) -> Vec<ProbabilityContour> {
        let mut contours = Vec::with_capacity(probabilities.len());

        for &probability in probabilities {
            let threshold = if probability >= 0.999_999 {
                self.occupied_threshold()
            } else {
                self.hdr_density_threshold(probability)
            };

            let Some(density_threshold) = threshold else {
                continue;
            };

            let rings = self.marching_squares(density_threshold);

            if !rings.is_empty() {
                contours.push(ProbabilityContour {
                    probability,
                    density_threshold,
                    rings,
                });
            }
        }

        contours
    }

    pub fn to_probability_contour_geojson(
        &self,
        probabilities: &[f32],
    ) -> String {
        let mut sorted_probabilities = probabilities.to_vec();
        sorted_probabilities.sort_by(|a, b| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));

        let contours =
            self.generate_probability_contours(&sorted_probabilities);

        let mut features = Vec::new();

        for contour in contours {
            for ring in contour.rings {
                if ring.len() < 3 {
                    continue;
                }

                let coordinates: Vec<Vec<f64>> = ring
                    .iter()
                    .map(|point| vec![point.x, point.y])
                    .collect();

                features.push(serde_json::json!({
                    "type": "Feature",
                    "geometry": {
                        "type": "Polygon",
                        "coordinates": [coordinates]
                    },
                    "properties": {
                        "concentration": contour.probability,
                    }
                }));
            }
        }

        serde_json::json!({
            "type": "FeatureCollection",
            "features": features
        })
        .to_string()
    }


    // ========================================================================
    // Marching squares
    // ========================================================================

    fn marching_squares(
        &self,
        threshold: f32,
    ) -> Vec<Vec<Point2D>> {
        if self.nx < 2 || self.ny < 2 {
            return Vec::new();
        }

        let mut polygons = Vec::new();

        let classified: Vec<u8> = self
            .grid
            .iter()
            .map(|&value| {
                if value.is_finite() && value >= threshold {
                    1
                } else {
                    0
                }
            })
            .collect();

        for y in 0..(self.ny - 1) {
            for x in 0..(self.nx - 1) {
                let idx = self.grid_index(x, y);
                let next_row_idx = self.grid_index(x, y + 1);

                let b0 = classified[idx];
                let b1 = classified[self.grid_index(x + 1, y)];
                let b2 = classified[self.grid_index(x + 1, y + 1)];
                let b3 = classified[next_row_idx];

                let config =
                    b0 | (b1 << 1) | (b2 << 2) | (b3 << 3);

                if config == 0 {
                    continue;
                }

                let lon = self.lon_min
                    + x as f64 * self.cell_size;
                let next_lon = lon + self.cell_size;

                let lat = self.lat_min
                    + y as f64 * self.cell_size;
                let next_lat = lat + self.cell_size;

                let p0 = Point2D { x: lon, y: lat };
                let p1 = Point2D {
                    x: next_lon,
                    y: lat,
                };
                let p2 = Point2D {
                    x: next_lon,
                    y: next_lat,
                };
                let p3 = Point2D {
                    x: lon,
                    y: next_lat,
                };

                if config == 15 {
                    polygons.push(vec![p0, p1, p2, p3]);
                    continue;
                }

                let c0 = self.grid[idx];
                let c1 = self.grid[self.grid_index(x + 1, y)];
                let c2 = self.grid[self.grid_index(x + 1, y + 1)];
                let c3 = self.grid[next_row_idx];

                let mb = Self::interpolate(
                    &p0,
                    &p1,
                    c0,
                    c1,
                    threshold,
                );

                let mr = Self::interpolate(
                    &p1,
                    &p2,
                    c1,
                    c2,
                    threshold,
                );

                let mt = Self::interpolate(
                    &p3,
                    &p2,
                    c3,
                    c2,
                    threshold,
                );

                let ml = Self::interpolate(
                    &p0,
                    &p3,
                    c0,
                    c3,
                    threshold,
                );

                let polygon = match config {
                    1 => vec![p0, mb, ml],
                    2 => vec![p1, mr, mb],
                    4 => vec![p2, mt, mr],
                    8 => vec![p3, ml, mt],

                    3 => vec![p0, p1, mr, ml],
                    6 => vec![p1, p2, mt, mb],
                    9 => vec![p0, p3, mt, mb],
                    12 => vec![p2, p3, ml, mr],

                    5 => vec![p0, mb, mr, p2, mt, ml],
                    10 => vec![mb, p1, mr, mt, p3, ml],

                    7 => vec![p0, p1, p2, mt, ml],
                    11 => vec![p0, p1, mr, mt, p3],
                    13 => vec![p0, mb, mr, p2, p3],
                    14 => vec![mb, p1, p2, p3, ml],

                    _ => Vec::new(),
                };

                if polygon.len() >= 3 {
                    polygons.push(polygon);
                }
            }
        }

        polygons
    }

    #[inline]
    fn interpolate(
        p1: &Point2D,
        p2: &Point2D,
        v1: f32,
        v2: f32,
        threshold: f32,
    ) -> Point2D {
        let difference = v2 - v1;

        if !difference.is_finite()
            || difference.abs() < 1.0e-10
        {
            return Point2D {
                x: (p1.x + p2.x) * 0.5,
                y: (p1.y + p2.y) * 0.5,
            };
        }

        let t = ((threshold - v1) / difference)
            .clamp(0.0, 1.0) as f64;

        Point2D {
            x: p1.x + t * (p2.x - p1.x),
            y: p1.y + t * (p2.y - p1.y),
        }
    }
}

// ============================================================================
// WASM bindings
// ============================================================================

#[wasm_bindgen]
pub struct HeatmapGenerator {
    grid: EulerianGrid,
}

#[wasm_bindgen]
impl HeatmapGenerator {
    #[wasm_bindgen(constructor)]
    pub fn new(
        lon_min: f64,
        lon_max: f64,
        lat_min: f64,
        lat_max: f64,
        cell_size: f64,
    ) -> Self {
        Self {
            grid: EulerianGrid::new(
                lon_min,
                lon_max,
                lat_min,
                lat_max,
                cell_size,
            ),
        }
    }

    pub fn clear(&mut self) {
        self.grid.clear();
    }

    pub fn add_particles(
        &mut self,
        lons: &[f64],
        lats: &[f64],
        weights: Option<Vec<f32>>,
    ) {
        self.grid.add_particles(
            lons,
            lats,
            weights.as_deref(),
        );
    }

    pub fn normalize_probability(&mut self) {
        self.grid.normalize_probability();
    }

    pub fn smooth(&mut self, n: usize) {
        for _ in 0..n {
            self.grid.smooth();
        }
    }

    pub fn to_contour_geojson(
        &self,
        thresholds: &[f32],
    ) -> String {
        self.grid.to_contour_geojson(thresholds)
    }

    pub fn to_probability_contour_geojson(
        &self,
        probabilities: &[f32],
    ) -> String {
        self.grid
            .to_probability_contour_geojson(probabilities)
    }

    pub fn probability_thresholds(
        &self,
        probabilities: &[f32],
    ) -> Vec<f32> {
        probabilities
            .iter()
            .map(|&probability| {
                if probability >= 0.999_999 {
                    self.grid
                        .occupied_threshold()
                        .unwrap_or(0.0)
                } else {
                    self.grid
                        .hdr_density_threshold(probability)
                        .unwrap_or(0.0)
                }
            })
            .collect()
    }
}