// ============================================================
// oil_library.rs
// Original five-oil library with bulk evaporation parameters.
// ============================================================

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OilType {
    MarineDiesel,
    BonnyLight,
    ArabianLight,
    VenezuelanHeavy,
    IFO380,
}

pub struct OilProperties {
    pub name: &'static str,
    pub api: f32,
    pub dynamic_viscosity_cp: f32,
    pub density_kgm3: f32,
    pub asphaltene_wt_pct: f32,
    pub wax_wt_pct: f32,
    pub y_w_final_max: f32,
    pub is_emulsion_stable: bool,
    pub f_evap_max: f32,
    pub c_evap_viscosity: f32,
    pub k0y: f32,
    pub molecular_weight: f32,
    pub henry_effective: f32,
    pub bulltime: f32,
    pub bullwinkle_fraction: f32,
}

impl OilType {
    pub fn properties(&self) -> OilProperties {
        match self {
            OilType::MarineDiesel => OilProperties {
                name: "Marine Diesel",
                api: 36.4,
                dynamic_viscosity_cp: 3.5,
                density_kgm3: 842.0,
                asphaltene_wt_pct: 0.0,
                wax_wt_pct: 0.05,
                y_w_final_max: 0.0,
                is_emulsion_stable: false,
                f_evap_max: 0.80,
                c_evap_viscosity: 3.0,
                k0y: 2.024e-06,
                molecular_weight: 0.228,
                henry_effective: 1.2e-6,
                bulltime: 3e34,
                bullwinkle_fraction: 1.0,
            },
            OilType::BonnyLight => OilProperties {
                name: "Bonny Light",
                api: 36.7,
                dynamic_viscosity_cp: 6.0,
                density_kgm3: 840.53,
                asphaltene_wt_pct: 0.8,
                wax_wt_pct: 8.0,
                y_w_final_max: 0.15,
                is_emulsion_stable: false,
                f_evap_max: 0.55,
                c_evap_viscosity: 5.0,
                k0y: 2.024e-06,
                molecular_weight: 0.190,
                henry_effective: 8.0e-7,
                bulltime: 43200.0,
                bullwinkle_fraction: 0.10,
            },
            OilType::ArabianLight => OilProperties {
                name: "Arabian Light",
                api: 32.1,
                dynamic_viscosity_cp: 13.0,
                density_kgm3: 864.0,
                asphaltene_wt_pct: 3.6,
                wax_wt_pct: 2.7,
                y_w_final_max: 0.56,
                is_emulsion_stable: true,
                f_evap_max: 0.40,
                c_evap_viscosity: 7.0,
                k0y: 2.024e-06,
                molecular_weight: 0.205,
                henry_effective: 5.0e-7,
                bulltime: 21600.0,
                bullwinkle_fraction: 0.08,
            },
            OilType::VenezuelanHeavy => OilProperties {
                name: "Bachequero Heavy",
                api: 14.0,
                dynamic_viscosity_cp: 10_000.0,
                density_kgm3: 971.66,
                asphaltene_wt_pct: 11.0,
                wax_wt_pct: 2.0,
                y_w_final_max: 0.80,
                is_emulsion_stable: true,
                f_evap_max: 0.06,
                c_evap_viscosity: 2.0,
                k0y: 2.024e-06,
                molecular_weight: 0.280,
                henry_effective: 8.0e-8,
                bulltime: 3600.0,
                bullwinkle_fraction: 0.03,
            },
            OilType::IFO380 => OilProperties {
                name: "IFO 380 LS",
                api: 11.3,
                dynamic_viscosity_cp: 25_000.0,
                density_kgm3: 990.0,
                asphaltene_wt_pct: 6.6,
                wax_wt_pct: 5.8,
                y_w_final_max: 0.85,
                is_emulsion_stable: true,
                f_evap_max: 0.08,
                c_evap_viscosity: 1.5,
                k0y: 2.024e-06,
                molecular_weight: 0.340,
                henry_effective: 1.0e-7,
                bulltime: 1800.0,
                bullwinkle_fraction: 0.02,
            },
        }
    }
}