[package]
name = "proteus-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
proteus-core = { path = "../proteus-core" }

# WASM bindings
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
js-sys = { workspace = true }
web-sys = { workspace = true }
gloo-net = { workspace = true }
console_error_panic_hook = { workspace = true }
serde-wasm-bindgen = { workspace = true }

# Ensure wasm-target getrandom backend
getrandom = { workspace = true }

# Shared
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }

# Init logging in browser
console_log = "1.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]